"""Seed realistic embroidery/POD product data into the products table."""
import asyncio
import sys
sys.path.insert(0, '.')

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from app.core.config import settings

engine = create_async_engine(settings.database_url, echo=False)
AsyncSessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

PRODUCTS = [
    {
        "source_platform": "etsy",
        "source_id": "etsy_001",
        "source_url": "https://www.etsy.com/listing/embroidered-custom-name-hat",
        "title": "Custom Embroidered Name Hat - Personalized Baseball Cap",
        "description": "High-quality custom embroidered baseball cap with your name or text. Perfect for gifts.",
        "category": "Accessories",
        "brand": None,
        "price": 28.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400",
        "sales_rank": 12,
        "sales_trend": 67.3,
        "review_count": 2847,
        "review_score": 4.8,
        "tiktok_views": 3500000,
        "facebook_ad_count": 85,
        "gmc_search_volume": 49500,
        "etsy_favorites": 8920,
        "profit_margin_estimate": 58.0,
        "sentiment_summary": "Customers love the quality and fast shipping. Main requests: more color options.",
        "pain_points": ["Limited color options", "Sizing runs small"],
        "ai_score": 94.0,
        "is_published": True,
    },
    {
        "source_platform": "amazon",
        "source_id": "amz_B09XK2",
        "source_url": "https://www.amazon.com/dp/B09XK2",
        "title": "Personalized Embroidered Tote Bag - Custom Name & Monogram",
        "description": "Canvas tote bag with custom embroidered name or monogram. Eco-friendly and durable.",
        "category": "Bags",
        "brand": None,
        "price": 24.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "sales_rank": 8,
        "sales_trend": 43.2,
        "review_count": 5670,
        "review_score": 4.6,
        "tiktok_views": 2100000,
        "facebook_ad_count": 112,
        "gmc_search_volume": 67200,
        "etsy_favorites": None,
        "profit_margin_estimate": 62.0,
        "sentiment_summary": "Buyers love the durability. Complaints about embroidery thread color fading.",
        "pain_points": ["Thread color fading", "Handle stitching could be stronger"],
        "ai_score": 89.0,
        "is_published": True,
    },
    {
        "source_platform": "etsy",
        "source_id": "etsy_003",
        "source_url": "https://www.etsy.com/listing/embroidered-hoodie-custom",
        "title": "Custom Embroidered Hoodie - Zodiac Signs & Star Constellation",
        "description": "Unisex heavyweight hoodie with custom zodiac embroidery. Ultra-soft fleece interior.",
        "category": "Apparel",
        "brand": None,
        "price": 49.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400",
        "sales_rank": 5,
        "sales_trend": 128.7,
        "review_count": 890,
        "review_score": 4.9,
        "tiktok_views": 8900000,
        "facebook_ad_count": 140,
        "gmc_search_volume": 38400,
        "etsy_favorites": 12300,
        "profit_margin_estimate": 71.0,
        "sentiment_summary": "Viral on TikTok. Customers obsessed with zodiac designs. High repeat purchase rate.",
        "pain_points": ["Wants more zodiac varieties", "Shipping time from US"],
        "ai_score": 97.0,
        "is_published": True,
    },
    {
        "source_platform": "tiktok",
        "source_id": "tt_video_001",
        "source_url": "https://www.tiktok.com/@shop/embroidered-patch-jacket",
        "title": "Embroidered Patch Denim Jacket - Vintage Floral Custom Design",
        "description": "Retro-style denim jacket with hand-crafted embroidered patches. Each piece is unique.",
        "category": "Apparel",
        "brand": None,
        "price": 79.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400",
        "sales_rank": 3,
        "sales_trend": 215.0,
        "review_count": 342,
        "review_score": 4.7,
        "tiktok_views": 15600000,
        "facebook_ad_count": 67,
        "gmc_search_volume": 22100,
        "etsy_favorites": None,
        "profit_margin_estimate": 55.0,
        "sentiment_summary": "Trending hard on TikTok. Young buyers love the vintage aesthetic.",
        "pain_points": ["High price point", "Limited sizes"],
        "ai_score": 92.0,
        "is_published": True,
    },
    {
        "source_platform": "etsy",
        "source_id": "etsy_005",
        "source_url": "https://www.etsy.com/listing/custom-embroidered-sweatshirt",
        "title": "Custom Name Embroidered Sweatshirt - Retro Block Font",
        "description": "Oversized crewneck sweatshirt with custom embroidered text in retro block font.",
        "category": "Apparel",
        "brand": None,
        "price": 44.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=400",
        "sales_rank": 15,
        "sales_trend": 38.5,
        "review_count": 1890,
        "review_score": 4.8,
        "tiktok_views": 1560000,
        "facebook_ad_count": 45,
        "gmc_search_volume": 31500,
        "etsy_favorites": 6780,
        "profit_margin_estimate": 65.0,
        "sentiment_summary": "Steady seller. Customers love the font choices and fabric quality.",
        "pain_points": ["More font options requested", "Color variety"],
        "ai_score": 86.0,
        "is_published": True,
    },
    {
        "source_platform": "amazon",
        "source_id": "amz_B08TZ1",
        "source_url": "https://www.amazon.com/dp/B08TZ1",
        "title": "Embroidered Baby Onesie - Custom Name Newborn Gift Set",
        "description": "Soft organic cotton onesie with cute custom embroidered name and animal design.",
        "category": "Baby",
        "brand": None,
        "price": 22.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1519689373023-dd07c7988603?w=400",
        "sales_rank": 22,
        "sales_trend": 52.1,
        "review_count": 3201,
        "review_score": 4.9,
        "tiktok_views": 980000,
        "facebook_ad_count": 78,
        "gmc_search_volume": 44300,
        "etsy_favorites": None,
        "profit_margin_estimate": 68.0,
        "sentiment_summary": "Perfect gift item. High conversion around holidays and baby showers.",
        "pain_points": ["Size options", "Gift packaging"],
        "ai_score": 88.0,
        "is_published": True,
    },
    {
        "source_platform": "facebook",
        "source_id": "fb_ad_001",
        "source_url": "https://www.facebook.com/marketplace/embroidered-pillow-cover",
        "title": "Custom Embroidered Throw Pillow Cover - Family Name & Est. Year",
        "description": "Linen blend pillow cover with custom family name and established year embroidery.",
        "category": "Home Decor",
        "brand": None,
        "price": 34.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400",
        "sales_rank": 18,
        "sales_trend": 29.4,
        "review_count": 567,
        "review_score": 4.7,
        "tiktok_views": 450000,
        "facebook_ad_count": 89,
        "gmc_search_volume": 18900,
        "etsy_favorites": None,
        "profit_margin_estimate": 72.0,
        "sentiment_summary": "Popular wedding and housewarming gift. Strong Facebook ad performance.",
        "pain_points": ["Pillow insert not included", "Font readability on darker fabrics"],
        "ai_score": 83.0,
        "is_published": True,
    },
    {
        "source_platform": "etsy",
        "source_id": "etsy_008",
        "source_url": "https://www.etsy.com/listing/embroidered-beanie-custom",
        "title": "Custom Embroidered Beanie - Personalized Winter Hat with Name",
        "description": "Warm knit beanie with custom embroidered name or initials. One size fits most.",
        "category": "Accessories",
        "brand": None,
        "price": 19.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=400",
        "sales_rank": 7,
        "sales_trend": 74.6,
        "review_count": 4320,
        "review_score": 4.6,
        "tiktok_views": 2800000,
        "facebook_ad_count": 55,
        "gmc_search_volume": 52100,
        "etsy_favorites": 9450,
        "profit_margin_estimate": 76.0,
        "sentiment_summary": "Seasonal best-seller. Holiday gift favorite. Fast shipping is key selling point.",
        "pain_points": ["Wants more color options", "Sizing for kids"],
        "ai_score": 91.0,
        "is_published": True,
    },
    {
        "source_platform": "tiktok",
        "source_id": "tt_video_002",
        "source_url": "https://www.tiktok.com/@shop/embroidered-bucket-hat",
        "title": "Embroidered Bucket Hat - Aesthetic Floral & Butterfly Designs",
        "description": "Y2K aesthetic bucket hat with intricate embroidered floral patterns. Unisex streetwear.",
        "category": "Accessories",
        "brand": None,
        "price": 23.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400",
        "sales_rank": 9,
        "sales_trend": 189.3,
        "review_count": 1230,
        "review_score": 4.5,
        "tiktok_views": 11200000,
        "facebook_ad_count": 92,
        "gmc_search_volume": 29700,
        "etsy_favorites": None,
        "profit_margin_estimate": 69.0,
        "sentiment_summary": "Massive TikTok virality. Gen Z target demo. Streetwear crossover appeal.",
        "pain_points": ["Stock availability", "Color fastness after wash"],
        "ai_score": 90.0,
        "is_published": True,
    },
    {
        "source_platform": "amazon",
        "source_id": "amz_B07PQ3",
        "source_url": "https://www.amazon.com/dp/B07PQ3",
        "title": "Personalized Embroidered Dog Bandana - Custom Pet Name",
        "description": "Soft cotton bandana with custom embroidered pet name. Perfect for dogs and cats.",
        "category": "Pet Supplies",
        "brand": None,
        "price": 14.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=400",
        "sales_rank": 4,
        "sales_trend": 61.8,
        "review_count": 6780,
        "review_score": 4.7,
        "tiktok_views": 4300000,
        "facebook_ad_count": 134,
        "gmc_search_volume": 61300,
        "etsy_favorites": None,
        "profit_margin_estimate": 78.0,
        "sentiment_summary": "Pet owners love personalization. Extremely high repeat purchase rate.",
        "pain_points": ["Bandana ties too long for small pets", "More pattern options"],
        "ai_score": 93.0,
        "is_published": True,
    },
    {
        "source_platform": "etsy",
        "source_id": "etsy_011",
        "source_url": "https://www.etsy.com/listing/embroidered-apron-custom",
        "title": "Custom Embroidered Kitchen Apron - Personalized Chef Gift",
        "description": "Professional cotton apron with custom embroidered name and title. Perfect chef gift.",
        "category": "Kitchen",
        "brand": None,
        "price": 32.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
        "sales_rank": 25,
        "sales_trend": 33.2,
        "review_count": 2100,
        "review_score": 4.8,
        "tiktok_views": 780000,
        "facebook_ad_count": 42,
        "gmc_search_volume": 24600,
        "etsy_favorites": 5340,
        "profit_margin_estimate": 63.0,
        "sentiment_summary": "Holiday and Father's Day hit. Strong repeat gifting occasion purchases.",
        "pain_points": ["Tie length for larger body types", "More pocket options"],
        "ai_score": 82.0,
        "is_published": True,
    },
    {
        "source_platform": "facebook",
        "source_id": "fb_ad_002",
        "source_url": "https://www.facebook.com/marketplace/embroidered-wedding-handkerchief",
        "title": "Custom Embroidered Wedding Handkerchief - Bride & Groom Names",
        "description": "Delicate linen handkerchief with custom embroidered names and wedding date.",
        "category": "Wedding",
        "brand": None,
        "price": 16.99,
        "currency": "USD",
        "main_image": "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400",
        "sales_rank": 11,
        "sales_trend": 45.7,
        "review_count": 1560,
        "review_score": 4.9,
        "tiktok_views": 620000,
        "facebook_ad_count": 68,
        "gmc_search_volume": 15800,
        "etsy_favorites": None,
        "profit_margin_estimate": 82.0,
        "sentiment_summary": "Wedding season staple. Brides love it as bridal party gift.",
        "pain_points": ["Packaging for gifting", "Font options"],
        "ai_score": 85.0,
        "is_published": True,
    },
]


async def seed():
    async with AsyncSessionLocal() as session:
        from sqlalchemy import text

        # Check if already seeded
        result = await session.execute(text("SELECT COUNT(*) FROM products"))
        count = result.scalar()
        if count > 0:
            print(f"Already has {count} products, skipping seed.")
            return

        # Insert products
        import json
        for p in PRODUCTS:
            await session.execute(
                text("""
                    INSERT INTO products (
                        source_platform, source_id, source_url, title, description,
                        category, brand, price, currency, main_image,
                        sales_rank, sales_trend, review_count, review_score,
                        tiktok_views, facebook_ad_count, gmc_search_volume, etsy_favorites,
                        profit_margin_estimate, sentiment_summary, pain_points, ai_score,
                        is_published, is_deleted
                    ) VALUES (
                        :source_platform, :source_id, :source_url, :title, :description,
                        :category, :brand, :price, :currency, :main_image,
                        :sales_rank, :sales_trend, :review_count, :review_score,
                        :tiktok_views, :facebook_ad_count, :gmc_search_volume, :etsy_favorites,
                        :profit_margin_estimate, :sentiment_summary, :pain_points, :ai_score,
                        :is_published, 0
                    )
                """),
                {**p, "pain_points": json.dumps(p["pain_points"])}
            )

        await session.commit()
        print(f"✅ Seeded {len(PRODUCTS)} products successfully!")


if __name__ == "__main__":
    asyncio.run(seed())
